backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Coffees"
    name: "coffees"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Price (€)", name: "price", widget: "number"}
  - label: "Food"
    name: "food"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Price (€)", name: "price", widget: "number"}
  - label: "Promo"
    name: "promo"
    create: true
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Price (€)", name: "price", widget: "number"}
