backend:
  name: git-gateway
  branch: master
 
media_folder: static/img
public_folder: /images
 
collections:
  - name: "Food"
    label: "Food"
    folder: "static/content/food/"
    create: true
    slug: "{{slug}}"
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Price (€)", name: "price", widget: "number" }
          - { 
            label: "Type",
            name: "type",
            widget: "select",
            options: ["pastery", "waffle", "superbowl"],
            default: "pastery",
            }
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "food",
            }
 
  - name: "Coffee"
    label: "Coffee"
    folder: "static/content/coffees"
    create: true
    slug: "{{slug}}"
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Price (€)", name: "price", widget: "number" }
          - { 
            label: "Type",
            name: "type",
            widget: "select",
            options: ["hot", "cold"],
            default: "hot",
            }
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "coffee",
            }

  - name: "Promotion"
    label: "Promotion"
    folder: "static/content/promotions"
    create: true
    slug: "{{slug}}"
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }
          - { label: "Price (€)", name: "price", widget: "number" }
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "promotion",
            }
