backend:
  name: git-gateway
  branch: master
 
media_folder: static/img
public_folder: /images
 
collections:
  - name: "Food"
    label: "Food"
    folder: "src/content/food/"
    create: true
    slug: "{{slug}}"
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "Description", widget: "markdown" }
          - { label: "Price (€)", name: "price", widget: "number" }
 
  - name: "Coffee"
    label: "Coffee"
    folder: "src/content/coffees"
    create: true
    slug: "{{slug}}"
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "Description", widget: "markdown" }
          - { label: "Price (€)", name: "price", widget: "number" }

  - name: "Promotion"
    label: "Promotion"
    folder: "src/content/promotions"
    create: true
    slug: "{{slug}}"
    fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "Description", widget: "markdown" }
          - { label: "Price (€)", name: "price", widget: "number" }
